config/jest.js

This PR disables `jest/lowercase-name` for describe blocks. It is common for describe blocks to be the name of a class, e.g. `MetaMaskController`, and this previously disallowed that.

Disable Jest lowercase-name for describe blocks

---

config/typescript.js

Refs #12
This PR updates our TS config, in response to comments on #25. I've removed any rules not listed under [_Supported Rules_ at `v2.20.0`](https://github.com/typescript-eslint/typescript-eslint/tree/v2.20.0/packages/eslint-plugin#supported-rules).
Also refs #2—this PR explicitly disables all of those rules.

Update all TypeScript rules, remove deprecated rules

---

config/typescript.js

This rule is disabled in the base config, it was mistakenly re-enabled in the TS config.

Disable @typescript-eslint/no-extra-parens

---

yarn.lock

This PR updates two deps to resolve the following two security advisories:
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ moderate      │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ minimist                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=1.2.3                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ eslint                                                       │
├───────────────┼──────────────────────────────────────────────────────── …
```

Use mkdirp@0.5.3 and minimist@1.2.5

---

yarn.lock

This PR updates our indirect dependency on `mkdirp` to the latest patch version

Use mkdirp@0.5.5

---

config/index.js

I don't think we should use this rule - mainly for the reasons outlined on the rule page itself; that using `async` is a useful shorthand for ensuring a function returns a Promise in all scenarios, particularly when an exception is thrown.
`async` also makes it very clear that a function returns a Promise, when it might otherwise be unclear at a glance because of uncertainty about what value is being `return`-ed.
There are some cases where we want to make a method `async` despite no asynchronous work being performed, just so that it conforms to an interface shared with other classes that _do_ need to be `async` (e.g. the keyrings).

Turn off `require-await` rule

---

config/index.js

This PR allows unary operators `++` and `--` in for loops.
See [`no-plusplus`](https://eslint.org/docs/rules/no-plusplus#options) options.

Relax no-plusplus rule

---

README.md

This PR adds the package version ranges to the README. These'll need to be updated for major versions but otherwise should work. ESLint and/or packages could've had major versions since the package has been updated and this is a way of expressing what this package works with. (Think `peerDependencies` but less annoying.)

Add package versions to README.md

---

config/index.js

I suggest that we set the maximum consecutive empty lines to 1. Currently it is set to 2, which is the default. The utility of this is unclear to me, and mostly it seems to introduce frustrating formatting inconsistencies in our code.

Set maximum consecutive empty lines to 1

---

config/index.js

Refs https://github.com/MetaMask/metamask-extension/pull/8535
Closes #43
This PR disallows all anonymous default exports. From the docs for the ESLint rule, emphasis mine:<sup>[\[1\]][1]</sup>
> Reports if a module's default export is unnamed. This includes several types of unnamed data types; literals, object expressions, arrays, anonymous functions, arrow functions, and anonymous class declarations.
>
> **Ensuring that default exports are named helps improve the grepability of the codebase by encouraging the re-use of the same identifier for the module's default export at its declaration site and at its import sites.**
[1]:https://github.com/benmosher/eslint-plugin-import/blob/v2.20.1/docs/rules/no-anonymous-default-export.md

Disallow all anonymous default exports

---

config/index.js

Closes #50
This disables `prefer-object-spread` as the rule presumes ES2018 which is a bit higher than some of the organization's projects currently support.

Disable prefer-object-spread

---

config/index.js

Refs MetaMask/metamask-extension#9263
Refs MetaMask/metamask-logo#35
This PR relaxes the [`prefer-destructuring`](https://eslint.org/docs/rules/prefer-destructuring) rule to no longer apply to arrays, object assignment, or renamed properties. That is, the following are allowed but not required:
```js
const first = array[0]; // before
const [first] = array; // after
```
```js
foo = obj.foo; // before
({ foo } = obj); // after
```
```js
const bar = obj.foo; // before
const { foo: bar } = obj; // afer
```

Relax prefer-destructuring rules

---

CHANGELOG.md

This PR fixes the version numbers in the changelog—v3.1.0 was incorrectly v3.0.1.

Fix version numbers in changelog

---

config/index.js
config/nodejs.js
package.json
yarn.lock

Refs #46
This change disables deprecated core Node.js/CommonJS rules in favour of rules from eslint-plugin-node.
From the docs:<sup>[\[1\]][1]</sup>
> The ten Node.js/CommonJS rules in core have been deprecated and moved to the eslint-plugin-node plugin.
[1]:https://eslint.org/docs/user-guide/migrating-to-7.0.0#deprecate-node-rules
All of the available eslint-plugin-node rules have been enabled.

Migrate to eslint-plugin-node

---

package.json
yarn.lock

Based on #58
Refs #46
This PR updates the direct dependencies to support ESLint v7.
ESLint itself:
- Updated `eslint` from `6.8.0...7.7.0`
- [_Migrating to v7.0.0_](https://eslint.org/docs/user-guide/migrating-to-7.0.0)
Other dependencies:
- Updated `@typescript-eslint/eslint-plugin` from `2.20.0...3.9.1`
- [Drops support for Node version 8](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v3.0.0)
- Updated `@typescript-eslint/parser` from `2.17.0...3.9.1`
- [Drops support for Node version 8](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v3.0.0)
- Updated `eslint-plugin-import` from `2.20.1...2.22.0`
- Updated `eslint-plugin-mocha` from `6.2.2...8.0.0`
- [Drop support for ESLint < v7 and Node.js < …

Update packages for ESLint v7

---

config/typescript.js

Closes #39
This PR changes [`space-before-function-paren`](https://eslint.org/docs/rules/space-before-function-paren) for TypeScript. There are examples of correct & incorrect code on the ESLint rule page.

Disable space-before-function-paren

---

config/typescript.js

This PR relaxes `@typescript-eslint/member-delimiter-style`, allowing prettier to auto-format TypeScript sources.

Relax member-delimiter-style for TypeScript

---

package.json

The two packages that are required by all configurations (`eslint` and `eslint-plugin-import`) have been added as `peerDependencies`. This makes the installation process slightly less error prone.

Add `peerDependencies`

---

config/nodejs.js

Refs https://github.com/MetaMask/eslint-config/pull/64#issuecomment-712957969
This rule does not offer support for ES2015 import/export syntax (ESM) which is supported by many of the other rules. Ensuring no invalid syntax is used is best left to the build tools/runtime.

Disable node/no-unsupported-features/es-syntax

---

config/nodejs.js

Refs https://github.com/MetaMask/eslint-config/pull/64#issuecomment-712959640
This rule is a duplicate of `import/extensions` as it only applies to ESM `import`s.

Disable node/file-extension-in-import

---

config/nodejs.js

Closes #74
This change disables the `node/no-missing-import` and `node/no-missing-require` as they duplicate functionality from `import/no-unresolved`.

Disable node/no-missing-* rules

---

.github/dependabot.yml

This change adds a GitHub Dependabot configuration to enable daily checks for dependency updates.
[See the docs for more information.][1]
This config enables checking for updates to the dev dependencies (`allow[0].dependency-type`) in the root `package.json` file (`directory`) every weekday (`schedule.interval`) and increasing the version range (if necessary, `versioning-strategy`). As I understand it, this would see minor and patch updates not touch the `package.json` file while major versions will include a change to the `package.json` file.
This ignores production dependencies as there are none, currently, _and_ because Dependabot doesn't support multiple update based on `allow[].dependency-type`.
[1]:https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/conf …

Add a GitHub Dependabot config

---

package.json
yarn.lock

- Major version bump of `@typescript-eslint` to from `3` to `4`
- This is to bring the package in line with `@typescript-eslint/eslint-plugin`
- Minor version bump of `@typescript-eslint/eslint-plugin`
- Because why not? The versions of both packages track.

@typescript-eslint/*@4.14.2

---

.eslintrc.js
package.json
packages/base/README.md
packages/base/package.json
packages/base/src/index.js
packages/jest/README.md
packages/jest/src/index.js
packages/mocha/README.md
packages/mocha/src/index.js
packages/nodejs/README.md
packages/nodejs/src/index.js
packages/typescript/README.md
packages/typescript/src/index.js
scripts/validate-prettier-rules.js
yarn.lock

This PR adds `prettier` to the base config, and updates its rules for `prettier` compatibility. It accomplishes this by copying [some relevant edge case rules from the extension](https://github.com/MetaMask/metamask-extension/blob/5a233e4/.eslintrc.js#L57-L106), extending the rules from `eslint-config-prettier`, and _disabling all rules overriding those `prettier` rules.
I tested it with the extension and it resulted in fairly minimal changes, mostly related to `quoteProps`.

Add prettier to base config

---

.eslintrc.js
packages/base/src/index.js
packages/typescript/src/index.js

Per [the docs](https://eslint.org/docs/user-guide/configuring/language-options#specifying-environments), we should just use `env`, and we failed to include appropriate globals in #149.

Fix EcmaScript version config

---

packages/base/package.json
packages/jest/package.json
packages/mocha/package.json
packages/nodejs/package.json
packages/typescript/package.json
yarn.lock

I don't know if we want this, but I've seen about 5s of perf improvements from just updating dependencies in extension. I know that nothing about these settings prevents that from happening in downstream consumers but seems appropriate to update the peer dependencies to encourage updates downstream.

update dev and peer deps

---

package.json

Adds the linting packages required for linting to the root manifest's `devDependencies`. Ref: https://github.com/MetaMask/eslint-config/pull/152#issuecomment-811913372

Add linting packages to root devDependencies

---

.prettierrc.yml

I have prettier for vscode installed with the option set to not format if a configuration file cannot be found.
I noticed, however, that on save it was turning single quote strings to double quote, which then showed as an error due to our eslint config.
Because this repo has an `.editorconfig` file, the prettier vscode plugin says "oh okay you really want me to format your files" and it follows the specs of that file. So I added the `.prettierrc.yml` file to prevent this behavior for anyone who might have my same experience.

add prettierrc.yml

---

packages/base/rules-snapshot.json
packages/base/src/index.js
packages/typescript/rules-snapshot.json
packages/typescript/src/index.js

This PR updates the configuration of [`no-shadow`](https://eslint.org/docs/7.0.0/rules/no-shadow) in the base config and replaces it with the `@typescript-eslint` version of the same rule to the TypeScript config.
The strictness of `no-shadow` is increased by forbidding the shadowing of built-in globals, e.g. `Object`, which for unknown reasons is permitted by default.
This probably makes the change breaking. Oh well.

Update no-shadow config

---

.prettierrc.yml
packages/base/rules-snapshot.json
packages/base/src/index.js

Closes #175 
We decided to use `as-needed` for Prettier's `quoteProps` option.

quoteProps: as-needed

---

packages/jest/package.json
packages/mocha/package.json
packages/nodejs/package.json
packages/typescript/package.json

We generally assume that anyone using our environment-specific packages is also using our base package. Our config validation assumes this as well, ensuring that there are no duplicate rules between them. As a result, anyone _not_ using the base package might have problems.
The base package has been added as a peer dependency everywhere to ensure consumers are warned about omitting the base package.

Add base package as a peer dependency

---

packages/base/README.md
packages/jest/README.md
packages/mocha/README.md
packages/nodejs/README.md
packages/typescript/README.md

The install instructions for each package had not been updated for the v6 release. They have all been updated to reference the correct package versions.

Update install instructions in READMEs

---

packages/base/package.json
packages/jest/package.json
packages/mocha/package.json
packages/nodejs/package.json
packages/typescript/package.json

Adds a script named `publish` to every `package.json` file so that you can do e.g. `yarn workspace path/to/workspace run publish` and `yarn workspaces run publish`.

Add publish script

---

.eslintrc.js
packages/base/src/index.js
packages/nodejs/src/index.js
packages/typescript/src/index.js

After upgrading to `7.0.0` of these packages in a couple of repositories, we encountered unexpected `import/unambiguous` rule violations. The reason for this turned out to be that we unintentionally set `parserOptions.sourceType` to `module` in some configs by extending the recommended ruleset of `eslint-plugin-import`. For the sake of simplicity, and minimizing breaking changes, we have decided to use `sourceType: script` by default for JavaScript, and `module` for TypeScript.
While debugging the above issue, we also noticed that the EcmaScript version was incorrectly set in places, probably due to related issues. According to the ESLint documentation, setting `env.es2017 = true` should automatically set `parserOptions.ecmaVersion = 2017`. It appears that this behavior is overridden by …

Fix parserOptions for various configs

---

packages/base/rules-snapshot.json
packages/base/src/index.js

This PR adds another condition where we apply the `padding-line-between-statements`, namely between multiline blocks and expressions. Whenever we forget to manually add newlines between multiline blocks and expressions, our files become significantly less navigable for those of us that use vim. It also makes our files cramped and harder to read, especially tests. 
We already tend to do this in practice, so this is best viewed as enforcing an existing, informal standard.
By way of example, `multiline-block-like` option results in the following change:
```javascript
/// before
if (foo) {
// stuff
}
if (bar) {
// stuff
}
/// after
if (foo) {
// stuff
}
if (bar) {
// stuff
}
```
While the `multiline-expression` option results in the following:
```javascript
/// before
it('does thing one', () …
```

Require newlines between multiline blocks and expressions

---

packages/typescript/rules-snapshot.json
packages/typescript/src/index.js

Fixes the `no-throw-literal` rule configuration for TypeScript by enabling the appropriate rule in the TypeScript config, per [documentation](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-throw-literal.md#how-to-use).
This is timely due to recent [changes to TypeScript](https://github.com/microsoft/TypeScript/pull/41013).

Fix no-throw-literal config for TypeScript

---

packages/typescript/CHANGELOG.md

One breaking change was accidentally omitted from the changelog. It has been restored, along with instructions on how to update your project to be compatible with this change.

Update v9.0.0 changelog for `@metamask/eslint-config-typescript`.

---

packages/typescript/rules-snapshot.json
packages/typescript/src/index.js

The rule `@typescript-eslint/no-throw-literal` has been disabled because it requires type information, which we hadn't realized when the rule was added. We're saving rules that require type information for a future release.
The rule that it extends (`no-throw-literal`) is left as disabled because it doesn't work properly with TypeScript (hence the existence of the extension rule).

Disable `@typescript-eslint/no-throw-literal`

---

packages/jest/CHANGELOG.md
packages/mocha/CHANGELOG.md
packages/nodejs/CHANGELOG.md
packages/typescript/CHANGELOG.md

The v8 entries for the non-base packages were left blank. They have been updated to explain the breaking change.

Add missing change entries for v8

---

packages/typescript/rules-snapshot.json
packages/typescript/src/index.js

TypeScript interfaces suck, they don't work with our `Json` type, and it's high time that we abolish them from every part of our codebase.
To wit, the only thing that can be done with an interface that cannot be done with a type is [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html), which is a "good language feature" in much the same way that a knife without a handle is a "good cooking instrument". All of the actually good stuff – IMO first and foremost `extends` and `implements` – [is also supported by object types](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#differences-between-type-aliases-and-interfaces) (in this case, via `&` and `implements`).
So, if we have two language features A and B, where the capabilities of A …

Forbid TypeScript interfaces

---

packages/mocha/src/index.js

Updates the `mocha` config `parserOptions.ecmaVersion` to `2020`. This allows us to use ES2020 features such as the spread operator in all its varied forms in our Mocha tests. We don't have to worry about compatibility for our end users because we're of course not shipping our tests anyway.

Update Mocha ecmaVersion

---

.github/workflows/lint-test.yml
yarn.lock

The lockfile was modified upon install after a recently merged PR. This PR fixes this and adds a clean working directory check to CI.

Add working directory check to CI, fix lockfile

---

packages/mocha/package.json
packages/mocha/rules-snapshot.json
yarn.lock

The only breaking changes are dropping of support for older versions of Node.js, and adding `mocha/no-empty-description` to the recommended configuration.

BREAKING: Update `eslint-plugin-mocha` from v8 to v10

---

packages/base/package.json
yarn.lock

The only breaking changes are dropping support for older versions of Node.js, ESLint, and prettier, none of which we use.

Update `eslint-plugin-prettier` from v3 to v4

---

.github/workflows/lint-test.yml
package.json
packages/base/package.json
packages/base/rules-snapshot.json
packages/jest/package.json
packages/mocha/package.json
packages/nodejs/package.json
packages/typescript/package.json
patches/eslint+8.21.0.patch
scripts/validate-configs.js
yarn.lock

ESLint has been updated to v8 in all packages. This lets us use the latest version of ESLint in our other packages without getting `peerDependency` mismatch warnings.
The main change to be aware of is that four new recommended rules have been added:
* [`no-loss-of-precision`](https://eslint.org/docs/latest/rules/no-loss-of-precision)
* [`no-nonoctal-decimal-escape`](https://eslint.org/docs/latest/rules/no-nonoctal-decimal-escape)
* [`no-unsafe-optional-chaining`](https://eslint.org/docs/latest/rules/no-unsafe-optional-chaining)
* [`no-useless-backreference`](https://eslint.org/docs/latest/rules/no-useless-backreference)
Our validation script was broken in this update because ESLint stopped exporting their recommended configuration. `patch-package` was added so that we could patch ESLint …

BREAKING: Update ESLint from v7 to v8

---

packages/typescript/rules-snapshot.json
packages/typescript/src/index.js

`private` fields and methods in TypeScript are not truly private. They can still be accessed in runtime. Using hash names (e.g., `#name`) makes them truly private, enforced by JavaScript itself.

Forbid TypeScript's private modifier in favour of hash names

---

packages/base/rules-snapshot.json
packages/base/src/index.js
scripts/validate-configs.js

I've added some configuration to the `import/order` rule, to make sure we automatically sort imports (fixable with `eslint --fix`). Imports will be sorted in two groups:
1. Node.js builtins and external modules (i.e., imports from `node_modules`).
2. Local (relative) imports.
Within these groups, imports are sorted alphabetically. A new line is placed between each import group, and the actual code.

Automatically sort imports

---

.editorconfig
.github/workflows/create-release-pr.yml
.github/workflows/lint-test.yml
.github/workflows/publish-release.yml
.gitignore
README.md
package.json
packages/base/package.json
packages/jest/package.json
packages/mocha/package.json
packages/nodejs/package.json
packages/typescript/package.json
yarn.lock

I've adapted this package to the latest module template standards. Due to the nature of this package, there are some differences between this and the module template:
- There are no build or test steps in the workflow, as we do not build anything and there are no tests.
- There is no documentation generation, as we do not have any JSDoc documentation.
- The publish workflow was adapted slightly to work without the need to build.
I've also updated `prettier` to the version used in the module template, and added `prettier-plugin-packagejson`.

Adapt package to latest module template standards

---

.eslintrc.js

We don't need to set the environment to `node` in our ESLint config because that is set by the Node.js config, which we extend from.

Remove redundant `env` entry

---

packages/nodejs/rules-snapshot.json
packages/nodejs/src/index.js

`import/no-nodejs-modules` was enabled in the base config in #242, but incorrectly not disabled in the Node.js config. I've fixed that here.

Disable `import/no-nodejs-modules` in Node.js config

---

packages/typescript/rules-snapshot.json
packages/typescript/src/index.js

Parameters can now use PascaleCase. This can be useful in cases where a class constructor is being passed as a parameter.

Allow parameters to use PascalCase

---

packages/typescript/rules-snapshot.json
packages/typescript/src/index.js

The lint rules have been updated to allow functions to be `async` even when they do not use `await`. It can be useful to make functions `async` sometimes even when `await` is not used, because it can simplify error handling for functions that return a Promise without `await`-ing it (it ensures errors are always rejected, not thrown). It can also be useful in cases when a function that does synchronous work needs to be async to match an interface.

Allow async functions without any 'await'

---

packages/base/rules-snapshot.json
packages/base/src/index.js

This effectively reverts #197. This rule is being removed because we have found that it forces us to introduce newlines in places where they obstruct readability rather than helping it.
When grouping statements, it is often useful to "chunk" related lines together by using a newline before and after the chunk, to denote that each of the statements are related in some way. This is often done in unit tests for example, when the "arrange", "act", "assert" grouping style is used. This rule was forcing us to break up chunks.

Stop requiring newlines between multiline blocks/expressions

---

packages/commonjs/CHANGELOG.md
packages/commonjs/LICENSE
packages/commonjs/README.md
packages/commonjs/jest.config.js
packages/commonjs/package.json
packages/commonjs/rules-snapshot.json
packages/commonjs/src/environment.json
packages/commonjs/src/index.js
packages/commonjs/src/index.test.js
scripts/generate-configs.js
yarn.lock

A new package has been added for CommonJS projects. Primarily this configuration will allow CommonJS globals such as `require`.
The environment config generation script was updated to support this new package. This required changes to allow combining both `shared-node-browser` and `commonjs` globals in the same configuration.

Add CommonJS ESLint configuration

---

packages/typescript/rules-snapshot.json
packages/typescript/src/index.js

The rule `@typescript-eslint/prefer-enum-initializers` has been added. This rule ensures that we use initializers for enums.
Uninitialized enums are hazardous because they implicitly assign each entry a sequential number value. This means that adding a new entry to the enum changes the value of every following entry. This can be confusing and unexpected, especially if this enum is stored in persisted state and now has a different meaning than before. Initialized enums, on the other hand, never unexpectedly change values.
This is a breaking change.

Add rule `@typescript-eslint/prefer-enum-initializers`

---

packages/typescript/rules-snapshot.json
packages/typescript/src/index.js

This pull request enables the `@typescript-eslint/consistent-type-imports` rule which helps to enforce the consistency
of writing type import statements across the codebase.
Without this rule, the following is allowed:
```ts
import { foo, bar, BazType } from 'package';
```
With this rule, it will automatically (upon running `eslint --fix`) turned into:
```ts
import type { BazType } from 'package';
import { foo, bar } from 'package';
```
1. Enable the `@typescript-eslint/consistent-type-imports` rule.

Enable `@typescript-eslint/consistent-type-imports` rule

---

packages/base/README.md
packages/base/package.json
packages/base/rules-snapshot.json
packages/base/src/index.js
packages/browser/README.md
packages/commonjs/README.md
packages/jest/README.md
packages/mocha/README.md
packages/nodejs/README.md
packages/typescript/README.md
yarn.lock

This pull request adds the `eslint-plugin-promise` package as a dependency to our project and adds the `no-multiple-resolved` rule to ESLint configuration with this plugin enabled. This avoids the error-prone situation where both `resolve()` and `reject()` can be called.
1. Add `eslint-plugin-promise` to the base package dependencies.
2. Add `no-multiple-resolved` rule to the ESLint configuration.
3. Update `rules-snapshot.json` to include the new rule.

Add `eslint-plugin-promise` and enable `no-multiple-resolved`

---

packages/typescript/rules-snapshot.json
packages/typescript/src/index.js

This pull request adds a new rule that enforces all generic parameters to have a length of at least 3 characters.
Before this change, this is allowed:
```ts
type Foo<T> = T;
``` 
After this change, you can do something like this instead:
```ts
type Foo<Type> = Type;
```
1. Add a new rule to enforce the minimum length of generic parameters at 3 characters.

Enforce generic parameter length of at least 3 characters

---

packages/commonjs/package.json
yarn.lock

The peer dependencies for `@metamask/commonjs` were accidentally duplicated from the base configuration when that package was created. They have been updated to refer just to ESLint and to the base config itself, as all the other config packages do.

Fix `@metamask/commonjs` peer dependencies

---

packages/typescript/rules-snapshot.json
packages/typescript/src/index.js

Enable the `@typescript-eslint/explicit-function-return-type` rule, which enforces that return types are specified for all functions. Being explicit about the return type makes it easier to see it without having to open the code in an editor, and communicating what a function _ought_ to return prevents bugs from sneaking in (in case the return value is not being tested).
---
Extracted from https://github.com/MetaMask/contributor-docs/pull/11#discussion_r1271137143.
Enabling this on `core` would produce 603 violations.
Enabling this on `snaps` would produce 571 violations.

Enforce specification of return types in TypeScript

---

.github/workflows/lint-test.yml
package.json
packages/base/package.json
packages/browser/package.json
packages/commonjs/package.json
packages/jest/package.json
packages/mocha/package.json
packages/nodejs/package.json
packages/typescript/package.json

Node.js 16 is EOL for some time now, so we can drop support for it. This is also a prerequisite for #370.

Drop support for Node.js <18.18

---

eslint.config.mjs
packages/base/README.md
packages/base/src/index.d.mts
packages/browser/README.md
packages/browser/src/index.mjs
packages/commonjs/README.md
packages/commonjs/src/index.mjs
packages/jest/README.md
packages/jest/src/index.mjs
packages/mocha/README.md
packages/mocha/src/index.mjs
packages/nodejs/README.md
packages/nodejs/src/index.mjs
packages/typescript/README.md
packages/typescript/src/index.mjs
packages/vitest/README.md
packages/vitest/src/index.mjs

Following #374, this updates all packages to use the `createConfig` helper function, including the READMEs.
I have not changed any rules, but removed all `files` arrays from the configs, so they can be configured in the consuming configurations (which is much easier now with `createConfig`).

Update all packages to use `createConfig`

---

package.json
packages/base/CHANGELOG.md
packages/base/README.md
packages/base/package.json
packages/browser/CHANGELOG.md
packages/browser/README.md
packages/browser/package.json
packages/commonjs/CHANGELOG.md
packages/commonjs/README.md
packages/commonjs/package.json
packages/jest/CHANGELOG.md
packages/jest/README.md
packages/jest/package.json
packages/mocha/CHANGELOG.md
packages/mocha/README.md
packages/mocha/package.json
packages/nodejs/CHANGELOG.md
packages/nodejs/README.md
packages/nodejs/package.json
packages/typescript/CHANGELOG.md
packages/typescript/README.md
packages/typescript/package.json
packages/vitest/CHANGELOG.md
packages/vitest/README.md
packages/vitest/package.json
yarn.lock

This reverts commit 597ecb60fc6332d3ebb1f99653f7905256b37ac0.
The release failed because the workflow assumes a `build` script exists, but we don't build anything in this repo. Will fix this in a separate PR.

Revert "Release 14.0.0 (#377)"

---

packages/typescript/rules-snapshot.json
packages/typescript/src/index.mjs

The bump to a more recent version of the TypeScript ESLint plugin added support for specifying naming conventions for import names (`import name from 'package';`). We didn't add a case for this, so the default format of `camelCase` applied, meaning that this is not allowed:
```ts
import SomeClass from 'some-package';
```
I've updated the rule to allow `camelCase`, `PascalCase`, `snake_case`, and `UPPER_CASE`, since the names of imports can depend on the (3rd party) package, and it feels unnecessary to enforce more strict formats in this case.

Loosen `@typescript-eslint/naming-convention` rule to allow more formats for import names

---

packages/jest/rules-snapshot.json
packages/jest/src/index.mjs

I propose that we remove this rule. I would argue that adding logic to tests is not as harmful as the docs for this rule would indicate and in fact can be quite useful.
- When mocking functions with overloads, it is necessary to add logic inside of the mock implementation to handle different arguments.
- When testing a function that can be called multiple ways where the behavior is mostly the same between inputs aside from a few edge cases, using an `if` statement to highlight the difference can be useful.

Remove jest/no-conditional-in-test rule

---

packages/typescript/rules-snapshot.json
packages/typescript/src/index.mjs
packages/typescript/tsconfig.json
tsconfig.json

Ref: https://github.com/MetaMask/ocap-kernel/pull/175
This replaces `@typescript-eslint/consistent-type-imports` with `import-x/consistent-type-specifier-style`, and an exhortation to enable `verbatimModuleSyntax` (requires TypeScript >=5) in the tsconfigs of our packages.
Heretofore, we have enforced the existence of type import specifiers, but not that they are stylistically consistent. The options are:
- "top-level", e.g. `import type { a } from 'x'}`
- "inline", e.g. `import { type a } from 'x'}`
The rule `@typescript-eslint/consistent-type-imports` has been responsible for this. This rule has an option named `fixTypes`, but that only applies when a type-only import is _not_ specified as a type-only import. In other words, it enforces the existence of type import specifiers, but not …

feat(typescript): Update type import specifier rules

---

packages/typescript/rules-snapshot.json
packages/typescript/src/index.mjs

This changes the `@typescript-eslint/prefer-promise-reject-errors` rule, which enforces that `Promise.reject` must be called with an instance of `Error`. After this change, `reject` may also be called with `unknown` values. For example, the following code was previously invalid, but is valid after this change:
```ts
new Promise((resolve, reject) => {
try {
return resolve(doSomething());
} catch (error) {
// `error` is of type `unknown`.
return reject(error);
}
});
```

Loosen `@typescript-eslint/prefer-promise-reject-errors` rule to allow rejecting with `unknown`

---

package.json
packages/typescript/README.md
packages/typescript/package.json
yarn.lock

This commit loosens the peer restriction on `typescript` to allow projects to upgrade to more recent versions of TypeScript (such as 5.8, the latest version at the time of writing). Similarly, the peer restriction on `typescript-eslint` has been loosened to support more recent versions.
Both of these packages have been updated in development as well.

Support TypeScript 5.6.x-5.8.x

---

packages/typescript/rules-snapshot.json
packages/typescript/src/index.mjs

This disables the `@typescript-eslint/no-unsafe-enum-comparison` rule, which disallows comparing enums to string or number values. For example, the following is not allowed when this rule is enabled:
```ts
enum Foo {
Bar = 'Bar',
Baz = 'Baz',
}
const myVariable: string = "Bar";
if (myVariable == Foo.Bar) {
// ...
}
```
We use this pattern in multiple places, so I think this rule is too strict and we should disable it.

Disable `@typescript-eslint/no-unsafe-enum-comparison` rule

---

README.md

The release documentation still referred to the old `create-release-pr` workflow that was replaced in #376
These instructions were copied from the `core` repository. Eventually I'd like to simplify them into one flow rather than two, but I figure we can sort that out later.

chore: Update release documentation
